### ISSUE TITLE
 Upgraded to MongoDb java driver 4.0.3

### ISSUE THREAD

**Issue by bjornharvold** [AxonFramework/extension-mongo#11]
Is it safe to exclude the MongoDb v3.x drivers from this module?

**Comment by bjornharvold** [comment]
Submitted a PR for this: https://github.com/AxonFramework/extension-mongo/pull/12

**Comment by bjornharvold** [comment]
Hi,

Do you guys have an ETA for v4.4?

Cheers

**Comment by smcvb** [comment]
FYI, we tend to not share specific dates at any time @bjornharvold.
To be on "the flip side" of this though, we aim to release 4.4 for Axon Server, Axon Framework and some of the extensions (like this one) somewhere this month.

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #12

**Comment by smcvb** [comment]
@bjornharvold, might be good to know that the 4.4 release of this extension has been released today! Please, give it a spin. :-)

**Comment by bjornharvold** [comment]
Will definitely do that!

**Comment by bjornharvold** [comment]
Only issue I see with upgrading to Spring Boot 2.3.x is Axon Server fails. I am not using Axon Server so I just excluded the auto configuration and everything runs fine.

```
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io.grpc.netty.NettyChannelBuilder
	at io.axoniq.axonserver.connector.AxonServerConnectionFactory$Builder.<init>(AxonServerConnectionFactory.java:246) ~[axonserver-connector-java-4.4.jar:4.4]
	at io.axoniq.axonserver.connector.AxonServerConnectionFactory.forClient(AxonServerConnectionFactory.java:145) ~[axonserver-connector-java-4.4.jar:4.4]
	at org.axonframework.axonserver.connector.AxonServerConnectionManager$Builder.build(AxonServerConnectionManager.java:214) ~[axon-server-connector-4.4.1.jar:4.4.1]
	at org.axonframework.springboot.autoconfig.AxonServerAutoConfiguration.platformConnectionManager(AxonServerAutoConfiguration.java:99) ~[axon-spring-boot-autoconfigure-4.4.1.jar:4.4.1]
	at org.axonframework.springboot.autoconfig.AxonServerAutoConfiguration$$EnhancerBySpringCGLIB$$659b72db.CGLIB$platformConnectionManager$1(<generated>) ~[axon-spring-boot-autoconfigure-4.4.1.jar:4.4.1]
	at org.axonframework.springboot.autoconfig.AxonServerAutoConfiguration$$EnhancerBySpringCGLIB$$659b72db$$FastClassBySpringCGLIB$$83c8696a.invoke(<generated>) ~[axon-spring-boot-autoconfigure-4.4.1.jar:4.4.1]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.axonframework.springboot.autoconfig.AxonServerAutoConfiguration$$EnhancerBySpringCGLIB$$659b72db.platformConnectionManager(<generated>) ~[axon-spring-boot-autoconfigure-4.4.1.jar:4.4.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_262]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 100 common frames omitted
```

**Comment by smcvb** [comment]
That's very helpful to know, thank you @bjornharvold.
