### ISSUE TITLE
Use Date type for date strings

### ISSUE THREAD

**Issue by smcvb** [AxonFramework/extension-mongo#72]
### Feature Description

Replace the date String fields for actual Date types.
Important in this process is to ensure the created sorting index (based on the event timestamp and sequence number) keeps a similar performance as it currently has.
Furthermore, we should make sure this adjustment keeps the current ordering based on timestamp and seqNo in working order.
 
### Current Behaviour

Currently, the Mongo Extension uses Strings to contain date times.

### Wanted Behaviour

The Mongo Extension should use the Date type to refer to date fields.

**Comment by marzelwidmer** [comment]
Hello @smcvb I try to migrate your Gamerental https://github.com/smcvb/gamerental Sample to use MongoDB.

Is the following Exception (on Read Model) I have when I use Jackson I mean when I save it as JSON (the Payload) in the DB.

```
at [Source: (byte[])"{"gameIdentifier":"12ACF52C3B-D026-48CC-9F25-925EFA50F4E4","title":"title....","releaseDate":1648226717.856000000,"description":"String","singleplayer":true,"multiplayer":true}"; line: 1, column: 129] (through reference chain: ch.keepcalm.coreapi.GameRegisteredEvent["description"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1991) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1219) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176) ~[jackson-datatype-jsr310-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._fromString(InstantDeserializer.java:307) ~[jackson-datatype-jsr310-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:217) ~[jackson-datatype-jsr310-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:51) ~[jackson-datatype-jsr310-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051) ~[jackson-databind-2.13.1.jar:2.13.1]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1529) ~[jackson-databind-2.13.1.jar:2.13.1]
	at org.axonframework.serialization.json.JacksonSerializer.deserialize(JacksonSerializer.java:202) ~[axon-messaging-4.5.8.jar:4.5.8]
	... 26 common frames omitted
Caused by: java.time.format.DateTimeParseException: Text 'String' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874) ~[na:na]
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._fromString(InstantDeserializer.java:301) ~[jackson-datatype-jsr310-2.13.1.jar:2.13.1]
	... 38 common frames omitted

```

**Comment by rsobies** [comment]
@smcvb you can assign it to me

**Comment by smcvb** [comment]
Ah, sorry to keep you waiting here, @rsobies. If anything, thanks for the enthusiasm to pick this up.
But, changing a column's type from several documents is quite a breaking change.

Hence, it is **not** something we can do in a minor or patch release.
At least, that's what we've decided on.

As such, this change is something to be done in tandem with the upcoming major release.
We are currently hard at work at getting AF5 ready, with still tons of work to do.
The extensions will follow, but I can't give you a date, sadly enough.

So, concerning your contribution, you can make a PR, and yes that should be done from `master`. 
But the chances of it getting merged soon are very slim. Sorry for that! 🙏 

Nonetheless, if you want to get a grasp of this **and** help us out for work the Framework team will eventually reach (I hope this year), then you are free to pick it up!
But do let me know whether the above discourages you. I would understand if you'd rather put your time and effort into something else.

**Comment by rsobies** [comment]
@smcvb no problem, I can take this one.

**Comment by smcvb** [comment]
Alright, thanks for that, @rsobies! I've assigned you to the ticket. Looking forward to the PR!
